### PR TITLE
Add entrypoints for intake_sql

### PR DESCRIPTION
**Pull request by ian-r-rose**
Adds entrypoints for the drivers specified in this repo.

### CODE REVIEW

**Comment by martindurant** [comment]
Definitely a good thing - don't know what happened with ibis here.

**Comment by ian-r-rose** [comment]
Er, weird. I'll look into it.

**Comment by martindurant** [comment]
No luck?

**Comment by ian-r-rose** [comment]
It resisted my initial attempt -- I'll take another look this week.

**Comment by ian-r-rose** [comment]
@martindurant Okay, I finally got a chance to look into this. The issue is an upstream bug in ibis, which necessitated pinning to the previous version of sqlalchemy. It has since been fixed, but has not been released yet, so until then it will need the pin.

**Comment by martindurant** [comment]
Glad you found it!

**Pull request merged**
